### ISSUE TITLE
VIRTUAL_HOST is broken in 1.4 when using yaml

### ISSUE THREAD

**Issue by aPoCoMiLogin** [docker/dockercloud-haproxy#61]
Hi, i'm trying to swap from `tutum/haproxy` to `dockercloud/haproxy` mostly because of certs from volume + swarm support (didn't tested swarm yet), but did run into issues. When using same yaml file what I was using for `tutum/haproxy`, version `dockercloud/haproxy:1.4` is throwing an error:

```
INFO:haproxy:dockercloud/haproxy 1.4 is running outside Docker Cloud
INFO:haproxy:Legacy link mode, loading HAProxy definition from environment variables: unable to connect to docker daemon ('Connection aborted.', error(2, 'No such file or directory'))
INFO:haproxy:dockercloud/haproxy PID: 6
INFO:haproxy:==========BEGIN==========
Traceback (most recent call last):
  File "/usr/bin/dockercloud-haproxy", line 9, in <module>
    load_entry_point('dockercloud-haproxy==1.4', 'console_scripts', 'dockercloud-haproxy')()
  File "/usr/lib/python2.7/site-packages/haproxy/main.py", line 53, in main
    run_haproxy()
  File "/usr/lib/python2.7/site-packages/haproxy/haproxycfg.py", line 24, in run_haproxy
    haproxy = Haproxy(config.LINK_MODE, msg)
  File "/usr/lib/python2.7/site-packages/haproxy/haproxycfg.py", line 47, in __init__
    self.specs = self._initialize(self.link_mode)
  File "/usr/lib/python2.7/site-packages/haproxy/haproxycfg.py", line 61, in _initialize
    specs = LegacyLinkSpecs()
  File "/usr/lib/python2.7/site-packages/haproxy/parser/legacy_link_parser.py", line 15, in __init__
    self._merge_services_with_same_vhost()
  File "/usr/lib/python2.7/site-packages/haproxy/parser/base_parser.py", line 27, in _merge_services_with_same_vhost
    for route in self.routes[service_alias]:
KeyError: 'DEVELOPMENT_WEBAPP'
```

my yaml file looks like:

```yaml
webapp:
  extends:
    file: ./webapp/docker-compose.yml
    service: webapp
  environment:
    VIRTUAL_HOST: 'https://webapp.local,webapp.local'
    APP_ENV: development
proxy:
  image: dockercloud/haproxy:1.4
  ports:
    - "127.0.0.1:80:80"
    - "127.0.0.1:443:443"
  volumes:
    - ./ssl/:/certs/
  environment:
    CA_CERT_FILE: /certs/cert.pem
  links:
    - webapp
```

but when I change version to `1.3` everything seems to work correctly. When `VIRTUAL_HOST` is deleted version `1.4` is not throwing an error. It seems that something is wrong with  `_merge_services_with_same_vhost` function. Unfortunately I don't know python well to tell what is wrong with that..

Also would be nice if there will be tests with docker-compose yaml files, same going for examples.

**Comment by tifayuki** [comment]
Thank you for reporting this. The issue has been fixed in 1.4.2

Thank you

**Comment by aPoCoMiLogin** [comment]
Thanks for fast response on this, but that didn't solve the problem, with `1.4.2` the issue still occurs:

```
WARNING: Tini has been relocated to /sbin/tini.
Please update your scripts to use /sbin/tini going forward.
/usr/bin/tini has been preserved for backwards compatibility in Alpine 3.4,
but WILL BE REMOVED in Alpine 3.5.

INFO:haproxy:dockercloud/haproxy 1.4.2 is running outside Docker Cloud
INFO:haproxy:Legacy link mode, loading HAProxy definition from environment variables: unable to connect to docker daemon ('Connection aborted.', error(2, 'No such file or directory'))
INFO:haproxy:dockercloud/haproxy PID: 6
INFO:haproxy:==========BEGIN==========
Traceback (most recent call last):
  File "/usr/bin/dockercloud-haproxy", line 9, in <module>
    load_entry_point('dockercloud-haproxy==1.4.2', 'console_scripts', 'dockercloud-haproxy')()
  File "/usr/lib/python2.7/site-packages/haproxy/main.py", line 53, in main
    run_haproxy()
  File "/usr/lib/python2.7/site-packages/haproxy/haproxycfg.py", line 24, in run_haproxy
    haproxy = Haproxy(config.LINK_MODE, msg)
  File "/usr/lib/python2.7/site-packages/haproxy/haproxycfg.py", line 47, in __init__
    self.specs = self._initialize(self.link_mode)
  File "/usr/lib/python2.7/site-packages/haproxy/haproxycfg.py", line 61, in _initialize
    specs = LegacyLinkSpecs()
  File "/usr/lib/python2.7/site-packages/haproxy/parser/legacy_link_parser.py", line 15, in __init__
    self._merge_services_with_same_vhost()
  File "/usr/lib/python2.7/site-packages/haproxy/parser/base_parser.py", line 27, in _merge_services_with_same_vhost
    for route in self.routes[service_alias]:
KeyError: 'DEVELOPMENT_WEBAPP'
```
There are few new errors too, also if I underestand it correctly, the issue occurs only in compose api v1 ? If so, I'll try to migrate whole project to new api, but you might want to solve the issue in legacy api too.

**Comment by tifayuki** [comment]
@aPoCoMiLogin 
It happens to only compose v1. Compose v1 links a service many times, which brings the issue.

I will take a look at it and add more tests.
Thank you :)

**Comment by aPoCoMiLogin** [comment]
One thing more, if you want still support v1 compose, don't know if you fixed it or not, but when I was using `tutum/haproxy` backends names were different sometimes, like it could be `SERVICE_WEBAPP` and `SERVICE_DEVELOPMENT_WEBAPP` and because of it, setting `default_backend`, was difficult to track it, so always had to change it manually.

**Comment by tifayuki** [comment]
@aPoCoMiLogin 
Can you also paste `./webapp/docker-compose.yml`?

I tried the following yml file and it works fine:
```
webapp:
  image: dockercloud/hello-world
  environment:
    VIRTUAL_HOST: 'https://webapp.local,webapp.local'
    APP_ENV: development
proxy:
  image: haproxy
  ports:
    - "127.0.0.1:80:80"
    - "127.0.0.1:443:443"
  volumes:
    - ./ssl/:/certs/
  environment:
    CA_CERT_FILE: /certs/cert.pem
  links:
    - webapp
```

**Comment by aPoCoMiLogin** [comment]
@tifayuki  the `webapp/docker-compose.yml` file is very simple and looks like this:

```yaml
webapp:
  image: nodejs
  working_dir: /app
  volumes:
      - ./:/app/
  expose:
      - "3000"
  restart: on-failure:5
  command: pm2 start /app/pm2.json --no-daemon
```

Just tried it now again and the result is same:

```
Traceback (most recent call last):
  File "/usr/bin/dockercloud-haproxy", line 9, in <module>
    load_entry_point('dockercloud-haproxy==1.4.2', 'console_scripts', 'dockercloud-haproxy')()
  File "/usr/lib/python2.7/site-packages/haproxy/main.py", line 53, in main
    run_haproxy()
  File "/usr/lib/python2.7/site-packages/haproxy/haproxycfg.py", line 24, in run_haproxy
    haproxy = Haproxy(config.LINK_MODE, msg)
  File "/usr/lib/python2.7/site-packages/haproxy/haproxycfg.py", line 47, in __init__
    self.specs = self._initialize(self.link_mode)
  File "/usr/lib/python2.7/site-packages/haproxy/haproxycfg.py", line 61, in _initialize
    specs = LegacyLinkSpecs()
  File "/usr/lib/python2.7/site-packages/haproxy/parser/legacy_link_parser.py", line 15, in __init__
    self._merge_services_with_same_vhost()
  File "/usr/lib/python2.7/site-packages/haproxy/parser/base_parser.py", line 27, in _merge_services_with_same_vhost
    for route in self.routes[service_alias]:
 KeyError: 'WEBAPP'
```

Is there a way, I can print you whole array before the error occurs ? Don't know python, so you have to show me some example, to paste you more details.

Also my setup looks like this: 
- ubuntu 16.04
- docker-compose version 1.7.1, build 0a9ab35
- Docker version 1.11.1, build 5604cbe

PS. sorry for my delay response..

**Comment by tifayuki** [comment]
@aPoCoMiLogin 
I replace the nodejs image with `dockercloud/hello-world`, and the compose file looks like:

```
webapp:
  extends:
    file: ./webapp/docker-compose.yml
    service: webapp
  environment:
    VIRTUAL_HOST: 'https://webapp.local,webapp.local'
    APP_ENV: development
proxy:
  image: dockercloud/haproxy:1.4.2
  ports:
    - "127.0.0.1:80:80"
    - "127.0.0.1:443:443"
  volumes:
    - ./ssl/:/certs/
  environment:
    CA_CERT_FILE: /certs/cert.pem
  links:
    - webapp
```

```
webapp:
  image: dockercloud/hello-world
  working_dir: /app
  volumes:
      - ./:/app/
  expose:
      - "3000"
```

And it gives me the output: 
```
Creating tmp_webapp_1
Creating tmp_proxy_1
Attaching to tmp_webapp_1, tmp_proxy_1
proxy_1   | WARNING: Tini has been relocated to /sbin/tini.
proxy_1   | Please update your scripts to use /sbin/tini going forward.
proxy_1   | /usr/bin/tini has been preserved for backwards compatibility in Alpine 3.4,
proxy_1   | but WILL BE REMOVED in Alpine 3.5.
proxy_1   | 
proxy_1   | INFO:haproxy:dockercloud/haproxy 1.4.2 is running outside Docker Cloud
proxy_1   | INFO:haproxy:Legacy link mode, loading HAProxy definition from environment variables: unable to connect to docker daemon ('Connection aborted.', error(2, 'No such file or directory'))
proxy_1   | INFO:haproxy:dockercloud/haproxy PID: 5
proxy_1   | INFO:haproxy:==========BEGIN==========
proxy_1   | INFO:haproxy:HAProxy configuration:
proxy_1   | global
proxy_1   |   log 127.0.0.1 local0
proxy_1   |   log 127.0.0.1 local1 notice
proxy_1   |   log-send-hostname
proxy_1   |   maxconn 4096
proxy_1   |   pidfile /var/run/haproxy.pid
proxy_1   |   user haproxy
proxy_1   |   group haproxy
proxy_1   |   daemon
proxy_1   |   stats socket /var/run/haproxy.stats level admin
proxy_1   |   ssl-default-bind-options no-sslv3
proxy_1   |   ssl-default-bind-ciphers ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES128-SHA:DHE-RSA-AES128-SHA:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA384:ECDHE-RSA-AES256-SHA:ECDHE-ECDSA-AES256-SHA:AES128-GCM-SHA256:AES128-SHA256:AES128-SHA:AES256-GCM-SHA384:AES256-SHA256:AES256-SHA:DHE-DSS-AES128-SHA:DES-CBC3-SHA
proxy_1   | defaults
proxy_1   |   balance roundrobin
proxy_1   |   log global
proxy_1   |   mode http
proxy_1   |   option redispatch
proxy_1   |   option httplog
proxy_1   |   option dontlognull
proxy_1   |   option forwardfor
proxy_1   |   timeout connect 5000
proxy_1   |   timeout client 50000
proxy_1   |   timeout server 50000
proxy_1   | listen stats
proxy_1   |   bind :1936
proxy_1   |   mode http
proxy_1   |   stats enable
proxy_1   |   timeout connect 10s
proxy_1   |   timeout client 1m
proxy_1   |   timeout server 1m
proxy_1   |   stats hide-version
proxy_1   |   stats realm Haproxy\ Statistics
proxy_1   |   stats uri /
proxy_1   |   stats auth stats:stats
proxy_1   | frontend port_443
proxy_1   |   bind :443  ca-file /certs/cert.pem verify required
proxy_1   |   reqadd X-Forwarded-Proto:\ https
proxy_1   |   maxconn 4096
proxy_1   |   acl is_websocket hdr(Upgrade) -i WebSocket
proxy_1   |   acl host_rule_1 hdr(host) -i webapp.local
proxy_1   |   acl host_rule_1_port hdr(host) -i webapp.local:443
proxy_1   |   use_backend SERVICE_WEBAPP if host_rule_1 or host_rule_1_port
proxy_1   | frontend port_80
proxy_1   |   bind :80
proxy_1   |   reqadd X-Forwarded-Proto:\ http
proxy_1   |   maxconn 4096
proxy_1   |   acl is_websocket hdr(Upgrade) -i WebSocket
proxy_1   |   acl host_rule_2 hdr(host) -i webapp.local
proxy_1   |   acl host_rule_2_port hdr(host) -i webapp.local:80
proxy_1   |   use_backend SERVICE_WEBAPP if host_rule_2 or host_rule_2_port
proxy_1   | backend SERVICE_WEBAPP
proxy_1   |   server TMP_WEBAPP_1 172.17.0.2:3000 check inter 2000 rise 2 fall 3
proxy_1   |   server TMP_WEBAPP_1 172.17.0.2:80 check inter 2000 rise 2 fall 3
proxy_1   | INFO:haproxy:Launching HAProxy
proxy_1   | INFO:haproxy:HAProxy has been launched(PID: 11)
proxy_1   | INFO:haproxy:===========END===========
```

Still cannot reproduce the issue :(

**Comment by aPoCoMiLogin** [comment]
Did dig into it a bit more, cause your example is working for me, while even simpler example with 2 linked services is not working for me:

```yaml
worker:
  image: dockercloud/hello-world
  environment:
    VIRTUAL_HOST: 'https://worker.local,worker.local'
storage:
  image: dockercloud/hello-world
  environment:
    VIRTUAL_HOST: 'https://storage.local,storage.local'
proxy:
  image: dockercloud/haproxy:1.4.2
  links:
    - worker
    - storage
```

results with: 

```
Creating test_worker_1
Creating test_storage_1
Creating test_proxy_1
Attaching to test_worker_1, test_storage_1, test_proxy_1
WARNING: Tini has been relocated to /sbin/tini.
Please update your scripts to use /sbin/tini going forward.
/usr/bin/tini has been preserved for backwards compatibility in Alpine 3.4,
but WILL BE REMOVED in Alpine 3.5.

INFO:haproxy:dockercloud/haproxy 1.4.2 is running outside Docker Cloud
INFO:haproxy:Legacy link mode, loading HAProxy definition from environment variables: unable to connect to docker daemon ('Connection aborted.', error(2, 'No such file or directory'))
INFO:haproxy:dockercloud/haproxy PID: 7
INFO:haproxy:==========BEGIN==========
Traceback (most recent call last):
  File "/usr/bin/dockercloud-haproxy", line 9, in <module>
    load_entry_point('dockercloud-haproxy==1.4.2', 'console_scripts', 'dockercloud-haproxy')()
  File "/usr/lib/python2.7/site-packages/haproxy/main.py", line 53, in main
    run_haproxy()
  File "/usr/lib/python2.7/site-packages/haproxy/haproxycfg.py", line 24, in run_haproxy
    haproxy = Haproxy(config.LINK_MODE, msg)
  File "/usr/lib/python2.7/site-packages/haproxy/haproxycfg.py", line 47, in __init__
    self.specs = self._initialize(self.link_mode)
  File "/usr/lib/python2.7/site-packages/haproxy/haproxycfg.py", line 61, in _initialize
    specs = LegacyLinkSpecs()
  File "/usr/lib/python2.7/site-packages/haproxy/parser/legacy_link_parser.py", line 15, in __init__
    self._merge_services_with_same_vhost()
  File "/usr/lib/python2.7/site-packages/haproxy/parser/base_parser.py", line 27, in _merge_services_with_same_vhost
    for route in self.routes[service_alias]:
KeyError: 'TEST_WORKER'
test_proxy_1 exited with code 1
```

Is there a way to print that array ?

**Comment by tifayuki** [comment]
@aPoCoMiLogin 
The example above raised an exception on my side.
There is no way to print out the array, but I will fix it ASAP.

Thank you

**Comment by Dids** [comment]
I'm trying to move my environments from Docker Cloud to Rancher, and since Rancher only supports Docker Compose v1, I'm now also running into this issue.

**Comment by tifayuki** [comment]
fixed in https://github.com/docker/dockercloud-haproxy/commit/2ee28ad85f3e436793dcf587117fc268087303fd, and built in `dockercloud/haproxy:staging`

I will publish a new version soon.

**Comment by aPoCoMiLogin** [comment]
@tifayuki did tested it and it seems to works fine.

sorry for my delay response..
